-- CreateEnum
CREATE TYPE "Permission" AS ENUM ('MANAGE_USERS', 'MANAGE_ROLES', 'VIEW_PATIENTS', 'EDIT_PATIENTS', 'VIEW_APPOINTMENTS', 'EDIT_APPOINTMENTS', 'VIEW_DASHBOARD');

-- AlterTable
ALTER TABLE "Patient" ADD COLUMN     "permissions" "Permission"[];
