name: Medsoft API CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node
          uses: actions/setup/node@v4
          with:
            node-version: 20
        - name: Install Dependencies
          run: npm install
        - name: Build TypeScript
          run: npm run build
        - name: Run Tests
          run: npm test
